### ISSUE TITLE
archived delete 

### ISSUE THREAD

**Issue by N-sherwood** [saltyorg/Saltbox#147]
Hello I think great idea for Backup so can we have delete automatic delete for old backup like one month old or set keep 2 archived at time by setting or cron 
 Thanks

**Comment by saltydk** [comment]
This would likely have to be a separate role seeing as we can offer no guarantees as to if it would end up deleting the only viable backup present, which is why we keep everything so that the user can sort that out themselves.

As per our discussions in the dev discord channel this has some downsides that we're not entirely sure if we can live with. Mostly the above. I am not opposed to making a role for it but it will not deliver any guarantee against backup data loss.
