### ISSUE TITLE
App Request: cowdsec

### ISSUE THREAD

**Issue by Nanefouad** [saltyorg/Saltbox#189]
hello everyone, I would like to submit the following proposal to you, it concerns Crowdsec. I would have liked to find it on the depo. thanks for making the necessary

**Comment by Barrow1990** [comment]
Is anyone actively working on this?
Id love to have this integrated

**Comment by Barrow1990** [comment]
# App name

CrowdSec is a free, modern & collaborative behavior detection engine, coupled with a global IP reputation network. It stacks on fail2ban's philosophy but is IPV6 compatible and 60x faster (Go vs Python), it uses Grok patterns to parse logs and YAML scenarios to identify behaviors. CrowdSec is engineered for modern Cloud / Containers / VM-based infrastructures (by decoupling detection and remediation). Once detected you can remedy threats with various bouncers (firewall block, nginx http 403, Captchas, etc.) while the aggressive IP can be sent to CrowdSec for curation before being shared among all users to further improve everyone's security. See [FAQ](https://doc.crowdsec.net/docs/faq) or read below for more.

## Links to further information

- [X] Link to project homepage or github | [Homepage](https://www.crowdsec.net/) | [Github](https://github.com/crowdsecurity/crowdsec)
- [X] Link to documentation | [Docs](https://doc.crowdsec.net/)
- [X] Link to installation instructions | [Docker Install Instructions](https://doc.crowdsec.net/u/getting_started/installation/docker)
- [X] Link to compose file | [Docker Compose](https://doc.crowdsec.net/u/getting_started/installation/docker)

## What are you willing to do to help?

- [X] I will you help with making docs if this gets picked up.
- [X] I will you help with testing.
- [X] Other things:- Help With Implementation Code

## Anything else you would like to add.

Not sure how this would be implemented due to requiring the following steps:
**This is based on [Example](https://www.crowdsec.net/blog/enhance-docker-compose-security)**
- How to automate the enrolling part
- How to automate the adding of the bouncer
- Modify the traefik container to depend on crowdsec as well as add the additional labels
- add additional labels to all other applications

They may be more steps but seems like a very heavy integration

**Comment by saltydk** [comment]
It is on my to do list.
