### ISSUE TITLE
Rclone Crypt support

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#55]
Relevant tasks needing work:
* Update cloudplow and/or crop to support rotation of service accounts when using rclone crypt backend. Possibly look into running rclone as a daemon so that we can use rclone remote control more easily.
* Update Plex Autoscan to use the Plex API instead of command line as it already contains crypt mapping support for drive monitoring.
* Add crypt as an option to the automated rclone remote setup (when it actually exists).

**Comment by Kha-kis** [comment]
Wanted to see if I can help on the 1st task listed.

"Update cloudplow and/or crop to support rotation of service accounts when using rclone crypt backend. Possibly look into running rclone as a daemon so that we can use rclone remote control more easily."

For this the rotation of the service accounts would need to be for the base remote as crypt wraps another remote.
Remote that is wrapped by crypt is where the service accounts need to be rotated. This is denoted in the rclone.conf for the crypt under the section "remote"

With this identification of the base remote we would be able to determine where we need to rotate the service accounts.

An example of this already being done is with gclone https://github.com/donwa/gclone where a config is added for the remotes to specify a service account file path.

I hope this helps!

**Comment by saltydk** [comment]
Yeah, it isn't hard but it also isn't really a high priority for me.

**Comment by saltydk** [comment]
For cloudplow/crop you can currently just duplicate your own remote with different SAs to get around it.

**Comment by saltydk** [comment]
Cloudplow has been updated to properly rotate service accounts in develop branch, l3uddz has been told how it was done so he'll have to decide if crop gets a similar treatment. PAS has been deprecated so ignoring that.
